[project]
name = "flaskhello"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.1",
]

[dependency-groups]
dev = [
    "pytest>=8.4.0",
]
